# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
parameters:
  client:
    type: boolean
    default: false
  server:
    type: boolean
    default: false

jobs:
  client:
    docker:
      - image: node:latest
    steps:
    - run: echo "This is client"

  server:
    docker:
     - image: node:latest
    steps:
      - run: echo "This is server"

workflows:
  version: 2
  client-flow:
    when: << pipeline.parameters.client >>
    jobs:
      - client

  server-flow:
    when: << pipeline.parameters.server >>
    jobs:
      - server
